.TH FS2GO 1 "Nov 2011" "fs2go\ VERSION"

.SH NAME
fs2go \- takeaway file system


.SH SYNOPSYS
.TP
.BR fs2go \ [ \-hv ]

.SS Mounting
.TP
.B fs2go
.RB [ \-fd ]
.RB [ \-o
.IR option [ \fB,\fPoption ]...]
.IR remotefs " " mountpoint
.SS Unmounting
.B fusermount -u
.I mountpoint


.SH DESCRIPTION
bla bla bla
.P
another paragraph lol


.SH OPTIONS

.SS "General options:"
.TP
.B -h\t\-\-help
print help

.TP
.B -v\t\-\-version
print version

.TP
.B -f\t\-\-foreground
don't fork to background

.TP
.B -d\t\-\-debug
enable debugging output, don't fork to background


.SS "fs2go options:"

.TP
.BI uid= uid
Change the process user to
.I uid
(name or numeric id) before mounting. Also changes group to
.I uid\fR's
primary group (unless
.I gid
is specified).

.TP
.BI gid= gid
Change the process group to
.I gid
(name or numeric id) before mounting.

.TP
.BI host= host
Hostname or IP adress of remote host. Whether pinging this host succeeds is a state criterion (see
.B STATE
below).

.TP
.BI pid= file
Path to a file containing a PID to check. Whether this PID is running is a state criterion (see
.B STATE
below).

.TP
.BI scan= secs
Wait
.I secs
seconds each interval before scanning remote fs for changed files (default is 10)

.TP
.BI conflict= mode
Conflict resolution mode (see
.B CONFLICTS
below). The
.I mode
argument can be either
.BR newer ", " mine " or " theirs
resulting in the following behaviour:
.RS
.RS
.BR newer ": Compare modification times of cached and remote file, keep the newer one"
.br
.BR mine ": Always keep cached file"
.br
.BR theirs ": Always keep remote file"
.RE
The default value is
.BR newer .
.RE

.TP
.BI bprefix= prefix \fR,\ \fPbsuffix= suffix
If at least one of these is specified, files or directories that would be removed during conflict handling (see
.B CONFLICTS
below) are being backed up by renaming them to
.RI < prefix >\fBfilename\fR< suffix >.

.TP
.B clear
Clear database and cache before mounting

.TP
.BI loglevel= level
Set logging level. The
.I level
argument can be either
.BR none ,\  error ,\  info ,\  verbose ,\  fsop \ or\  debug ,
each one including its predecessors (e.g. using
.B verbose
will also print
.BR info \ and\  error
messages).
.br
The default value is
.BR none .

.TP
.BI logfile= file
File to append log messages to. If not specified,
.I stderr
will be used.

.TP
.BI no-mode
Don't synchronize file access permssions (chmod) between cache and remote

.TP
.BI no-owner
Don't synchronize file user ownership

.TP
.BI no-group
Don't synchronize file group ownership

.TP
.BI no-xattr
Don't synchronize extended attributes (if supported at all)

.TP
.BI nfs
like
.IR no-owner , no-group

.TP
.BI sshfs
like
.IR no-owner , no-group , no-xattr

.SS "Advanced options:"
.TP
.BI db= file
File to use for sqlite db

.TP
.BI cache= dir
Cache directory

.SS STATE
